// Bootstrap
export const SET_LOCALE = 'SET_LOCALE';
export const TOGGLE_THEME = 'TOGGLE_THEME';

// Coins API
export const FETCH_COINS_FRONT = 'FETCH_COINS_FRONT';
export const FETCH_COINS_FRONT_FAILURE = 'FETCH_COINS_FRONT_FAILURE';
export const FETCH_COINS_FRONT_SUCCESS = 'FETCH_COINS_FRONT_SUCCESS';
