// Bootstrap
export const SET_LOCALE = 'SET_LOCALE';
export const SET_DARK_THEME = 'SET_DARK_THEME';

// Coins API
export const FETCH_COINS_DATA = 'FETCH_COINS_DATA';
export const FETCH_COINS_DATA_FAILURE = 'FETCH_COINS_DATA_FAILURE';
export const FETCH_COINS_DATA_SUCCESS = 'FETCH_COINS_DATA_SUCCESS';
export const FETCH_COINS_LIST = 'FETCH_COINS_LIST';
export const FETCH_COINS_LIST_FAILURE = 'FETCH_COINS_LIST_FAILURE';
export const FETCH_COINS_LIST_SUCCESS = 'FETCH_COINS_LIST_SUCCESS';
